name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: N3blXvyG7Tz8DHO9Fiv9GEsRbDdejt1zT96U
          GIST_ID: 6f95b52afbf712b499798f6d42156b05
          WAKATIME_API_KEY: cfeeb2a7-ee1f-47aa-b642-e75216a4c77c
          TIMEZONE: Asia/Seoul
